- job: 
  name: yang_fetch-vqfx-devel-py2
  description: Yang fetch job on vqfx with devel branch and Python 2
  parent: ansible-role-tests-vqfx-devel-py2
  vars:
    test_entrypoint: yang_fetch/test.yaml

- project:
    check:
      jobs:
        - ansible-test-sanity
        - ansible-role-tests-devel-py2
        - ansible-role-tests-2.6-py2
        - ansible-role-tests-2.6-py3
        - yang_fetch-vqfx-devel-py2
    gate:
      jobs:
        - ansible-test-sanity
        - ansible-role-tests-devel-py2
        - ansible-role-tests-2.6-py2
        - ansible-role-tests-2.6-py3
        - yang_fetch-vqfx-devel-py2
